### ISSUE TITLE
Covering folder input without any images for automatic cell counting

### ISSUE THREAD

**Issue by PhilippB1990** [PhilippB1990/Cell_Image_Analyser#1]
*Script version*:
- 1.0

*Feature version*:
- 1.0

*Operating System*:
- Win 10

*Steps to reproduce*:

- start tool
- choose folder without any images
- choose "automatic cell counting"
- proceed by applying any parameters

*Expected results*:
- output that no images in folder

*Actual results*:
- unhandled error output

*Additional information*:

File "C:\Users\Computer\OneDrive\Projects\Git Repositories\Cell_Image_Analyser\CIA_1.0.py", line 1943, in <module>
    saveCountResults(CountDic)
  File "C:\Users\Computer\OneDrive\Projects\Git Repositories\Cell_Image_Analyser\CIA_1.0.py", line 1373, in saveCountResults
    results.write("Average time per image	" + str(finalTime/globalImageCount) + "\n")
  File "D:\Fiji.app\jars\jython-shaded-2.5.3.jar\Lib\datetime.py", line 638, in __div__
ZeroDivisionError: long division or modulo

	at org.python.core.Py.ZeroDivisionError(Py.java:255)
	at org.python.core.PyLong.divide(PyLong.java:401)
	at org.python.core.PyLong.long___floordiv__(PyLong.java:458)
	at org.python.core.PyLong.__floordiv__(PyLong.java:450)
	at org.python.core.PyObject._basic_floordiv(PyObject.java:2453)
	at org.python.core.PyObject._floordiv(PyObject.java:2439)
	at datetime$py.__div__$38(D:\Fiji.app\jars\jython-shaded-2.5.3.jar\Lib\datetime.py:639)
	at datetime$py.call_function(D:\Fiji.app\jars\jython-shaded-2.5.3.jar\Lib\datetime.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:149)
	at org.python.core.PyFunction.__call__(PyFunction.java:327)
	at org.python.core.PyMethod.__call__(PyMethod.java:124)
	at org.python.core.PyMethod.__call__(PyMethod.java:115)
	at org.python.core.PyObject._binop_rule(PyObject.java:1935)
	at org.python.core.PyObject._div(PyObject.java:2329)
	at org.python.pycode._pyx1.saveCountResults$35(C:\Users\Computer\OneDrive\Projects\Git Repositories\Cell_Image_Analyser\CIA_1.0.py:1387)
	at org.python.pycode._pyx1.call_function(C:\Users\Computer\OneDrive\Projects\Git Repositories\Cell_Image_Analyser\CIA_1.0.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:134)
	at org.python.core.PyFunction.__call__(PyFunction.java:317)
	at org.python.pycode._pyx1.f$0(C:\Users\Computer\OneDrive\Projects\Git Repositories\Cell_Image_Analyser\CIA_1.0.py:1975)
	at org.python.pycode._pyx1.call_function(C:\Users\Computer\OneDrive\Projects\Git Repositories\Cell_Image_Analyser\CIA_1.0.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1275)
	at org.scijava.plugins.scripting.jython.JythonScriptEngine.eval(JythonScriptEngine.java:76)
	at org.scijava.script.ScriptModule.run(ScriptModule.java:177)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:167)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:126)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:65)
	at org.scijava.thread.DefaultThreadService$2.call(DefaultThreadService.java:191)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by PhilippB1990** [comment]
Issue fixed, exception added
